version: '3.8'

services:

  isucon-go:
    build:
      context: ./go
    ports:
      - "8080:8080"
    restart: always

  isucon-java:
    build:
      context: ./java
    ports:
      - "8081:8080"
    restart: always

  isucon-python:
    build:
      context: ./python
    ports:
      - "8082:5000"
    restart: always

  isucon-mysql:
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: isu4_qualifier
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/sql:/sql
